version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=twitter-clone
    ports:
      - 3306:3306
    volumes:
      - twitter-clone-mysql-data:/var/lib/mysql
      - twitter-clone-mysql-config:/etc/mysql
  # node_backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DBNAME: twitter-clone
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: 123123
  #     MYSQL_HOST: db
  #   volumes:
  #     - ./:/nodejs_hello
  #   ports:
  #     - "3030:3030"
  #   depends_on:
  #     - db

volumes:
  twitter-clone-mysql-data:
  twitter-clone-mysql-config:
